# Название нашего workflow
name: CI/CD

# Запускаем его по git push
on: [push]

# Здесь описываются jobs, т.е задачи, возникающие в рамках этого workflow
jobs:
  # Задача build описывает процесс сборки проекта
  build:
    # Выбираем, на какой ОС будет выполняться задача
    # А если подробнее - какой образ Docker используется
    runs-on: ubuntu-latest

    # Шаги задачи
    steps:
      # Копируем репозиторий во временную папку
      - uses: actions/checkout@v2

      # Устанавливаем JDK версии 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Проверяем работоспособность Gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      # Запускаем команду gradle build и пробуем в принципе собрать проект
      - name: Build with Gradle
        run: ./gradlew build